# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('chandao_id', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True)),
                ('finish_date', models.DateTimeField(blank=True)),
                ('last_time', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('serial', models.IntegerField()),
                ('finish_date', models.DateTimeField(blank=True)),
                ('last_time', models.IntegerField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Mission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('serial', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='step',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Type'),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Status'),
        ),
        migrations.AddField(
            model_name='progress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Step'),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Status'),
        ),
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Type'),
        ),
    ]
